const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_ONE_CUSTOMER: 'GET_ONE_CUSTOMER',
    GET_ALL_CUSTOMER: 'GET_ALL_CUSTOMER',
    UPDATE_CUSTOMER_SUCCES : 'UPDATE_CUSTOMER_SUCCES',
    UPDATE_CUSTOMER_FAIL : 'UPDATE_CUSTOMER_FAIL',

    GET_ALL_TABLE : 'GET_ALL_TABLE',
    GET_ONE_TABLE : 'GET_ONE_TABLE',
    ADD_TABLE_SUCCESS : 'ADD_TABLE_SUCCESS',
    ADD_TABLE_FAIL : 'ADD_TABLE_FAIL',
    DELETE_TABLE_SUCCESS: "DELETE_TABLE_SUCCESS",
    DELETE_TABLE_FAIL: "DELETE_TABLE_FAIL",
    UPDATE_TABLE_SUCCESS : 'UPDATE_TABLE_SUCCESS',
    UPDATE_TABLE_FAIL : 'UPDATE_TABLE_FAIL'

    
}

export default actionTypes;