const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_ONE_CUSTOMER: 'GET_ONE_CUSTOMER',
    GET_ALL_CUSTOMER: 'GET_ALL_CUSTOMER',
    UPDATE_CUSTOMER_SUCCES : 'UPDATE_CUSTOMER_SUCCES',
    UPDATE_CUSTOMER_FAIL : 'UPDATE_CUSTOMER_FAIL',
}

export default actionTypes;