const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_ONE_CUSTOMER: 'GET_ONE_CUSTOMER',
    GET_ALL_CUSTOMER: 'GET_ALL_CUSTOMER',
    UPDATE_CUSTOMER_SUCCES : 'UPDATE_CUSTOMER_SUCCES',
    UPDATE_CUSTOMER_FAIL : 'UPDATE_CUSTOMER_FAIL',

    GET_ALL_TABLE : 'GET_ALL_TABLE',
    GET_ONE_TABLE : 'GET_ONE_TABLE',
    ADD_TABLE_SUCCESS : 'ADD_TABLE_SUCCESS',
    ADD_TABLE_FAIL : 'ADD_TABLE_FAIL',
    DELETE_TABLE_SUCCESS: "DELETE_TABLE_SUCCESS",
    DELETE_TABLE_FAIL: "DELETE_TABLE_FAIL",
    UPDATE_TABLE_SUCCESS : 'UPDATE_TABLE_SUCCESS',
    UPDATE_TABLE_FAIL : 'UPDATE_TABLE_FAIL',

    GET_ALL_FOOD : 'GET_ALL_FOOD',
    GET_ONE_FOOD : 'GET_ONE_FOOD',
    ADD_FOOD_SUCCESS : 'ADD_FOOD_SUCCESS',
    ADD_FOOD_FAIL : 'ADD_FOOD_FAIL',
    DELETE_FOOD_SUCCESS: "DELETE_FOOD_SUCCESS",
    DELETE_FOOD_FAIL: "DELETE_FOOD_FAIL",
    UPDATE_FOOD_SUCCESS : 'UPDATE_FOOD_SUCCESS',
    UPDATE_FOOD_FAIL : 'UPDATE_FOOD_FAIL',

    GET_ALL_CATEGORY : 'GET_ALL_CATEGORY',
    GET_ONE_CATEGORY : 'GET_ONE_CATEGORY',
    ADD_CATEGORY_SUCCESS : 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL : 'ADD_CATEGORY_FAIL',
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",
    UPDATE_CATEGORY_SUCCESS : 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL : 'UPDATE_CATEGORY_FAIL',

    GET_ALL_EMPLOYEE : 'GET_ALL_EMPLOYEE',
    ADD_ORDER_STAFF_SUCCESS : 'ADD_ORDER_STAFF_SUCCESS',
    ADD_ORDER_STAFF_FAIL : 'ADD_ORDER_STAFF_FAIL',
    ADD_CHEF_STAFF_SUCCESS : 'ADD_CHEF_STAFF_SUCCESS',
    ADD_CHEF_STAFF_FAIL : 'ADD_CHEF_STAFF_FAIL',
    DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
    DELETE_EMPLOYEE_FAIL: "DELETE_EMPLOYEE_FAIL",
    UPDATE_EMPLOYEE_SUCCESS : 'UPDATE_EMPLOYEE_SUCCESS',
    UPDATE_EMPLOYEE_FAIL : 'UPDATE_EMPLOYEE_FAIL'

    
}

export default actionTypes;