const actionTypes= {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_ALL_TABLE : 'GET_ALL_TABLE',
    GET_ONE_EMPLOYEE: 'GET_ONE_EMPLOY',
    GET_ALL_HALL : 'GET_ALL_HALL',
    UPDATE_TABLE_SUCCESS : 'UPDATE_TABLE_SUCCESS',
    UPDATE_TABLE_FAIL : 'UPDATE_TABLE_FAIL',

    GET_ORDER:"GET_ORDER",
    UPDATE_STATUS_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
    UPDATE_STATUS_ORDER_FAIL: "UPDATE_ORDER_FAIL",
    UPDATE_STATUS_FOOD_SUCCESS: "UPDATE_FOOD_SUCCESS",
    UPDATE_STATUS_FOOD_FAIL: "UPDATE_FOOD_FAIL",
}

export default actionTypes