export { default as Admin } from './admin'
export { default as AdminHome } from './adminHome'
export { default as Food } from './food'
export { default as Customer } from './customer'
export { default as OrderStaff } from './orderStaff'
export { default as ChefStaff } from './chefStaff'
export { default as Table } from './table'
export { default as DetailFood } from './detailFood'
